# Generated by Django 4.1.5 on 2023-01-06 05:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CarcaseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carcase_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MotorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motor_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyPurpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_purpose", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyRentalPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rental_period", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleCarcaseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carcase_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleDriveUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drive_unit", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Use the following format: <YYYY>",
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2023),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobAd",
            fields=[
                (
                    "ad_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="forarmenians_app.ad",
                    ),
                ),
                ("work_graphic", models.CharField(max_length=155)),
                ("salary", models.IntegerField()),
                ("experience", models.CharField(max_length=50)),
            ],
            bases=("forarmenians_app.ad",),
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="forarmenians_app.vehiclebrand",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyAdd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(max_length=100)),
                ("badrooms", models.PositiveIntegerField()),
                ("bathrooms", models.PositiveIntegerField()),
                ("square", models.PositiveIntegerField()),
                (
                    "ad_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forarmenians_app.ad",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forarmenians_app.propertycategory",
                    ),
                ),
                (
                    "property_purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forarmenians_app.propertypurpose",
                    ),
                ),
                (
                    "rental_period",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forarmenians_app.propertyrentalperiod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="static/img/ads_photos")),
                (
                    "ad_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forarmenians_app.ad",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forarmenians_app.country",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forarmenians_app.state",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ad",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="forarmenians_app.address",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="VehicleAd",
            fields=[
                (
                    "ad_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="forarmenians_app.ad",
                    ),
                ),
                ("engine_volume", models.IntegerField()),
                ("mileage", models.CharField(max_length=100)),
                ("power", models.IntegerField()),
                ("price", models.IntegerField()),
                (
                    "carcase_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forarmenians_app.vehiclecarcasetype",
                    ),
                ),
                (
                    "drive_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forarmenians_app.vehicledriveunit",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to="forarmenians_app.vehiclemodel",
                    ),
                ),
                (
                    "motor_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forarmenians_app.motortype",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="forarmenians_app.vehicleyear",
                    ),
                ),
            ],
            bases=("forarmenians_app.ad",),
        ),
        migrations.CreateModel(
            name="LanguageSkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=50)),
                ("level", models.CharField(max_length=50)),
                (
                    "job_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forarmenians_app.jobad",
                    ),
                ),
            ],
        ),
    ]
