# Generated by Django 4.1.5 on 2023-01-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forarmenians_app", "0002_alter_vehiclead_power"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehiclebrand", old_name="model", new_name="brand",
        ),
        migrations.AlterField(
            model_name="vehiclead",
            name="power",
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
