# Generated by Django 4.1.5 on 2023-01-06 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forarmenians_app", "0005_alter_vehiclemodel_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclemodel",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="forarmenians_app.vehiclebrand",
            ),
        ),
    ]
